// Generated by github.com/romshark/toki. DO NOT EDIT.

package tokibundle

import (
	"fmt"
	"io"
	"time"

	locales "github.com/go-playground/locales"
	locale "github.com/go-playground/locales/de"
	language "golang.org/x/text/language"
)

// This prevents the "imported and not used" error when some features are not used.
var (
	_ fmt.Formatter = nil
	_ time.Time

	tr_de  = locale.New()
	loc_de = language.MustParse("de")
)

type catalog_de struct{}

var writers_de = map[string]func(w io.Writer, args ...any) (int, error){
	msg67d55c3a4cd41132: func(w io.Writer, args ...any) (written int, err error) {
		return wrs(w, "Verbinde...")
	},
	msg6c474fd0c1450d76: func(w io.Writer, args ...any) (written int, err error) {
		return wrs(w, "Bewege den Mauszeiger, um servergesteuerte Reaktivität zu sehen. Jede visuelle Änderung läuft über Go-Handler via SSE.")
	},
	msg92b7f0313afa09d6: func(w io.Writer, args ...any) (written int, err error) {
		return wrs(w, "Latenz")
	},
	msgb2b13b2baddf9df9: func(w io.Writer, args ...any) (written int, err error) {
		return wrs(w, "Live")
	},
	msgc949fe3a738759d7: func(w io.Writer, args ...any) (written int, err error) {
		return wrs(w, "Impulse")
	},
	msgf193004842edd5a2: func(w io.Writer, args ...any) (written int, err error) {
		return wrs(w, "Servergesteuerte Hypermedia für Go")
	},
	msgffb5de65e993a32e: func(w io.Writer, args ...any) (written int, err error) {
		return wrs(w, "Verbindung")
	},
}

func (catalog_de) Locale() language.Tag { return loc_de }

func (catalog_de) Translator() locales.Translator { return tr_de }

func (catalog_de) String(tik string, args ...any) string {
	b := poolBufGet()
	defer poolBufPut(b)
	f := writers_de[tik]
	if f == nil {
		_, _ = MissingTranslation(b, loc_de, tik, args...)
	} else {
		_, _ = f(b, args...)
	}
	return b.String()
}

func (catalog_de) Write(
	writer io.Writer, tik string, args ...any,
) (written int, err error) {
	f := writers_de[tik]
	if f == nil {
		return MissingTranslation(writer, loc_de, tik, args...)
	}
	return f(writer, args...)
}
