// Generated by github.com/romshark/toki. DO NOT EDIT.

package tokibundle

import (
	"fmt"
	"io"
	"time"

	locales "github.com/go-playground/locales"
	locale "github.com/go-playground/locales/fr"
	language "golang.org/x/text/language"
)

// This prevents the "imported and not used" error when some features are not used.
var (
	_ fmt.Formatter = nil
	_ time.Time

	tr_fr  = locale.New()
	loc_fr = language.MustParse("fr")
)

type catalog_fr struct{}

var writers_fr = map[string]func(w io.Writer, args ...any) (int, error){
	msg67d55c3a4cd41132: func(w io.Writer, args ...any) (written int, err error) {
		return wrs(w, "Connexion en cours...")
	},
	msg6c474fd0c1450d76: func(w io.Writer, args ...any) (written int, err error) {
		return wrs(w, "Déplacez votre curseur pour voir la réactivité pilotée par le serveur. Chaque changement visuel passe par des handlers Go via SSE.")
	},
	msg92b7f0313afa09d6: func(w io.Writer, args ...any) (written int, err error) {
		return wrs(w, "Latence")
	},
	msgb2b13b2baddf9df9: func(w io.Writer, args ...any) (written int, err error) {
		return wrs(w, "En direct")
	},
	msgc949fe3a738759d7: func(w io.Writer, args ...any) (written int, err error) {
		return wrs(w, "Impulsions")
	},
	msgf193004842edd5a2: func(w io.Writer, args ...any) (written int, err error) {
		return wrs(w, "Hypermédia piloté par le serveur pour Go")
	},
	msgffb5de65e993a32e: func(w io.Writer, args ...any) (written int, err error) {
		return wrs(w, "Connexion")
	},
}

func (catalog_fr) Locale() language.Tag { return loc_fr }

func (catalog_fr) Translator() locales.Translator { return tr_fr }

func (catalog_fr) String(tik string, args ...any) string {
	b := poolBufGet()
	defer poolBufPut(b)
	f := writers_fr[tik]
	if f == nil {
		_, _ = MissingTranslation(b, loc_fr, tik, args...)
	} else {
		_, _ = f(b, args...)
	}
	return b.String()
}

func (catalog_fr) Write(
	writer io.Writer, tik string, args ...any,
) (written int, err error) {
	f := writers_fr[tik]
	if f == nil {
		return MissingTranslation(writer, loc_fr, tik, args...)
	}
	return f(writer, args...)
}
