// Generated by github.com/romshark/toki. DO NOT EDIT.

package tokibundle

import (
	"fmt"
	"io"
	"time"

	locales "github.com/go-playground/locales"
	locale "github.com/go-playground/locales/ja"
	language "golang.org/x/text/language"
)

// This prevents the "imported and not used" error when some features are not used.
var (
	_ fmt.Formatter = nil
	_ time.Time

	tr_ja  = locale.New()
	loc_ja = language.MustParse("ja")
)

type catalog_ja struct{}

var writers_ja = map[string]func(w io.Writer, args ...any) (int, error){
	msg67d55c3a4cd41132: func(w io.Writer, args ...any) (written int, err error) {
		return wrs(w, "接続中...")
	},
	msg6c474fd0c1450d76: func(w io.Writer, args ...any) (written int, err error) {
		return wrs(w, "カーソルを動かすと、サーバー駆動のリアクティビティが見られます。すべての視覚的な変化は SSE 経由で Go ハンドラーを通ります。")
	},
	msg92b7f0313afa09d6: func(w io.Writer, args ...any) (written int, err error) {
		return wrs(w, "レイテンシ")
	},
	msgb2b13b2baddf9df9: func(w io.Writer, args ...any) (written int, err error) {
		return wrs(w, "ライブ")
	},
	msgc949fe3a738759d7: func(w io.Writer, args ...any) (written int, err error) {
		return wrs(w, "パルス")
	},
	msgf193004842edd5a2: func(w io.Writer, args ...any) (written int, err error) {
		return wrs(w, "Go のためのサーバー駆動ハイパーメディア")
	},
	msgffb5de65e993a32e: func(w io.Writer, args ...any) (written int, err error) {
		return wrs(w, "接続")
	},
}

func (catalog_ja) Locale() language.Tag { return loc_ja }

func (catalog_ja) Translator() locales.Translator { return tr_ja }

func (catalog_ja) String(tik string, args ...any) string {
	b := poolBufGet()
	defer poolBufPut(b)
	f := writers_ja[tik]
	if f == nil {
		_, _ = MissingTranslation(b, loc_ja, tik, args...)
	} else {
		_, _ = f(b, args...)
	}
	return b.String()
}

func (catalog_ja) Write(
	writer io.Writer, tik string, args ...any,
) (written int, err error) {
	f := writers_ja[tik]
	if f == nil {
		return MissingTranslation(writer, loc_ja, tik, args...)
	}
	return f(writer, args...)
}
