// Generated by github.com/romshark/toki. DO NOT EDIT.

package tokibundle

import (
	"fmt"
	"io"
	"time"

	locales "github.com/go-playground/locales"
	locale "github.com/go-playground/locales/en"
	language "golang.org/x/text/language"
)

// This prevents the "imported and not used" error when some features are not used.
var (
	_ fmt.Formatter = nil
	_ time.Time

	tr_en  = locale.New()
	loc_en = language.MustParse("en")
)

type catalog_en struct{}

var writers_en = map[string]func(w io.Writer, args ...any) (int, error){
	msg67d55c3a4cd41132: func(w io.Writer, args ...any) (written int, err error) {
		return wrs(w, "Connecting...")
	},
	msg6c474fd0c1450d76: func(w io.Writer, args ...any) (written int, err error) {
		return wrs(w, "Move your cursor to see server-driven reactivity. Every visual change flows through Go handlers via SSE.")
	},
	msg92b7f0313afa09d6: func(w io.Writer, args ...any) (written int, err error) {
		return wrs(w, "Latency")
	},
	msgb2b13b2baddf9df9: func(w io.Writer, args ...any) (written int, err error) {
		return wrs(w, "Live")
	},
	msgc949fe3a738759d7: func(w io.Writer, args ...any) (written int, err error) {
		return wrs(w, "Pulses")
	},
	msgf193004842edd5a2: func(w io.Writer, args ...any) (written int, err error) {
		return wrs(w, "Server-driven hypermedia for Go")
	},
	msgffb5de65e993a32e: func(w io.Writer, args ...any) (written int, err error) {
		return wrs(w, "Connection")
	},
}

func (catalog_en) Locale() language.Tag { return loc_en }

func (catalog_en) Translator() locales.Translator { return tr_en }

func (catalog_en) String(tik string, args ...any) string {
	b := poolBufGet()
	defer poolBufPut(b)
	f := writers_en[tik]
	if f == nil {
		_, _ = MissingTranslation(b, loc_en, tik, args...)
	} else {
		_, _ = f(b, args...)
	}
	return b.String()
}

func (catalog_en) Write(
	writer io.Writer, tik string, args ...any,
) (written int, err error) {
	f := writers_en[tik]
	if f == nil {
		return MissingTranslation(writer, loc_en, tik, args...)
	}
	return f(writer, args...)
}
